### ISSUE TITLE
Debrid & Trakt auths are not saved in Linux

### ISSUE THREAD

**Issue by cg00001** [a4k-openproject/script.module.myaccounts#1]
I tried several times to save Trakt & Premiumize authorizations but checking settings.xml they are not there.
Obviously addons using My Accounts don't work.
![ksnip_20200927-094856](https://user-images.githubusercontent.com/38960370/94358388-3d215600-00a9-11eb-94f4-12a210c3ca76.png)

**Comment by Tinuz97** [comment]
@Tikipeter

**Comment by cg00001** [comment]
> @Tikipeter

I've read your issue on Fen -and all other ones-, no matter how I try, Trakt & debrid auths are not saved, I tried via Fenom Scrapers, Venom, Fen, and simply My accounts, then synced the addons.
Nothing is written on that xml, while eg Fen searches, scanning seems to work and shows sources gathering but gets no results in movie/series.

**Comment by cg00001** [comment]
I managed to authorize Trakt & Premiumize simply by clicking on Defaults first in both sections.
